# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                 ryan:
                        password: ryanpass
                        roles: 'ROLE_USER'
                 admin:
                        password: $2y$12$UxjhUhZ7E2LNhGYZRICmqeii3L3Yp/HhGIARMXDF2RHSRkbZdwuuW
                        roles: 'ROLE_ADMIN'


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
            http_basic: ~

        main:
            anonymous: ~
            form_login:
                login_path: belajarlagi
                check_path: belajarlagi

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        AppBundle\Entity\Akun : bcrypt
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/belajarlagi,roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/keluaraja, roles: ROLE_USER }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
